spring:
  cloud:
    sentinel:
      datasource:
        gw-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            dataId: ${spring.application.name}-flow-rules.json
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: gw-flow
    gateway:
      routes:
        - id: system
          uri: lb://system
          predicates:
            - Path=/back-end/sys-*/**,/back-end/sharding-*/**
          filters:
            - StripPrefix=1
        - id: flowable
          uri: lb://flowable
          predicates:
            - Path=/back-end/flowable-*/**
          filters:
            - StripPrefix=1
        - id: crm
          uri: lb://crm
          predicates:
            - Path=/back-end/crm-*/**
          filters:
            - StripPrefix=1
        - id: report
          uri: lb://report
          predicates:
            - Path=/back-end/report-*/**
          filters:
            - StripPrefix=1
        - id: doc
          uri: lb://doc
          predicates:
            - Path=/back-end/doc-*/**
          filters:
            - StripPrefix=1
        - id: job
          uri: lb://job
          predicates:
            - Path=/back-end/job-*/**
          filters:
            - StripPrefix=1
        - id: mobile
          uri: lb://mobile
          predicates:
            - Path=/back-end/mobile-*/**
          filters:
            - StripPrefix=1
lego:
  open-request-log: true
  # 防止XSS攻击
  xss:
    enabled: false
    excludeUrls:
      - /back-end/sys-notice-template/**
      - /back-end/report-definition/**
      - /back-end/flowable-model/**
  # 不校验白名单
  ignore:
    urls:
      - /back-end/sys-index/**
      - /back-end/mobile-login/**